"""
artifacts/code_skeleton.py
Person B — Generates a downloadable code skeleton zip from the
Backend Architect Agent JSON.

Generated structure inside the zip:
  <project_name>/
    main.py          (FastAPI scaffold with all endpoints)
    models.py        (Pydantic models from schema)
    routes.py        (Router stubs for every endpoint)
    database.py      (SQLAlchemy setup)
    requirements.txt
    .env.example
    README.md
    docker-compose.yml

Usage:
    generate_code_skeleton(backend_spec, idea, session_dir)
    # Writes: session_dir/code_skeleton.zip
"""

from __future__ import annotations

import io
import os
import re
import zipfile
from pathlib import Path
from textwrap import dedent
from typing import Any


# ─────────────────────────────────────────────────────────────────────────────
# Public API
# ─────────────────────────────────────────────────────────────────────────────

def generate_code_skeleton(
    backend_spec: dict[str, Any],
    idea: str,
    session_dir: Path,
) -> Path:
    """
    Generate a downloadable code skeleton .zip from backend_spec.

    Args:
        backend_spec: Backend Architect Agent JSON.
        idea:         Original startup idea (used for project naming).
        session_dir:  Output directory.

    Returns:
        Path to the written .zip file.
    """
    project_name = _to_snake(idea)[:30] or "startup_backend"
    out_path = session_dir / "code_skeleton.zip"

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:

        def add(filename: str, content: str) -> None:
            zf.writestr(f"{project_name}/{filename}", dedent(content).lstrip("\n"))

        # Handle both live Gemini format (entities list) and fallback format (database_schema dict)
        entities = backend_spec.get("entities", [])
        schema_raw = backend_spec.get("database_schema", {})
        if entities:
            schema = {e["name"]: e.get("fields", []) for e in entities if isinstance(e, dict)}
        else:
            schema = schema_raw

        # Handle both live Gemini format (api_endpoints list-of-dicts) and fallback (key_endpoints list-of-strings)
        raw_endpoints = backend_spec.get("api_endpoints") or backend_spec.get("key_endpoints", [])
        endpoints = [
            f"{ep['method']} {ep['path']}" if isinstance(ep, dict) else ep
            for ep in raw_endpoints
        ]

        tech      = backend_spec.get("tech_choices", {})
        services  = backend_spec.get("services", [])
        arch      = backend_spec.get("architecture", "FastAPI + PostgreSQL")

        add("main.py",           _render_main(project_name, endpoints, tech))
        add("models.py",         _render_models(schema, project_name))
        add("routes.py",         _render_routes(endpoints, project_name))
        add("database.py",       _render_database(tech))
        add("requirements.txt",  _render_requirements(tech))
        add(".env.example",      _render_env_example(tech))
        add("docker-compose.yml", _render_docker_compose(project_name, tech))
        add("README.md",         _render_readme(project_name, idea, arch, services, endpoints, tech))

    out_path.write_bytes(buf.getvalue())
    return out_path


# ─────────────────────────────────────────────────────────────────────────────
# File renderers
# ─────────────────────────────────────────────────────────────────────────────

def _render_main(project_name: str, endpoints: list[str], tech: dict) -> str:
    auth_middleware = """
from fastapi.security import OAuth2PasswordBearer
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")
""" if "jwt" in str(tech).lower() else ""

    return f'''"""
{project_name}/main.py
Generated by AI Co-Founder Team — Backend Architect Agent
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
import os

from routes import router
from database import Base, engine
{auth_middleware}
load_dotenv()

# Create database tables
Base.metadata.create_all(bind=engine)

app = FastAPI(
    title="{project_name.replace("_", " ").title()} API",
    description="Generated by AI Co-Founder Team",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("CORS_ORIGINS", "*").split(","),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.get("/health")
async def health():
    return {{"status": "ok", "version": "0.1.0"}}
'''


def _render_models(schema: dict, project_name: str) -> str:
    model_blocks = []
    for table_name, columns in schema.items():
        class_name = _to_pascal(table_name)
        fields = []
        pydantic_fields = []
        for col in columns:
            if col == "id":
                fields.append("    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)")
                pydantic_fields.append("    id: Optional[int] = None")
            elif "date" in col or "_at" in col:
                fields.append(f"    {col}: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)")
                pydantic_fields.append(f"    {col}: Optional[datetime] = None")
            elif "_id" in col:
                fields.append(f"    {col}: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)")
                pydantic_fields.append(f"    {col}: Optional[int] = None")
            elif col in ("status", "type", "role"):
                fields.append(f"    {col}: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)")
                pydantic_fields.append(f"    {col}: Optional[str] = None")
            elif col in ("salary", "total_amount"):
                fields.append(f"    {col}: Mapped[Optional[float]] = mapped_column(Float, nullable=True)")
                pydantic_fields.append(f"    {col}: Optional[float] = None")
            else:
                fields.append(f"    {col}: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)")
                pydantic_fields.append(f"    {col}: Optional[str] = None")

        alchemy_block = (
            f"class {class_name}(Base):\n"
            f'    __tablename__ = "{table_name}"\n'
            + "\n".join(fields)
        )
        pydantic_block = (
            f"class {class_name}Schema(BaseModel):\n"
            + "\n".join(pydantic_fields)
            + "\n\n"
            + f"    class Config:\n"
            + f"        from_attributes = True"
        )
        model_blocks.append(alchemy_block + "\n\n\n" + pydantic_block)

    blocks_str = "\n\n\n# " + "─" * 70 + "\n\n\n".join(model_blocks) if model_blocks else "# No schema provided"

    return f'''"""
{project_name}/models.py
SQLAlchemy ORM models + Pydantic schemas
"""
from __future__ import annotations
from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, Float, Integer, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from pydantic import BaseModel

from database import Base


{blocks_str}
'''


def _render_routes(endpoints: list[str], project_name: str) -> str:
    route_stubs = []
    for ep in endpoints:
        parts = ep.strip().split(" ", 1)
        if len(parts) != 2:
            continue
        method, path = parts
        method = method.lower()
        func_name = _path_to_func(method, path)
        response_hint = "dict"

        if method == "get":
            stub = (
                f'@router.{method}("{path}", response_model={response_hint})\n'
                f"async def {func_name}():\n"
                f'    """TODO: implement — {ep}"""\n'
                f"    raise HTTPException(status_code=501, detail=\"Not implemented\")"
            )
        elif method in ("post", "put", "patch"):
            stub = (
                f'@router.{method}("{path}")\n'
                f"async def {func_name}(data: dict):\n"
                f'    """TODO: implement — {ep}"""\n'
                f"    raise HTTPException(status_code=501, detail=\"Not implemented\")"
            )
        else:
            stub = (
                f'@router.{method}("{path}")\n'
                f"async def {func_name}():\n"
                f'    """TODO: implement — {ep}"""\n'
                f"    raise HTTPException(status_code=501, detail=\"Not implemented\")"
            )
        route_stubs.append(stub)

    stubs_str = "\n\n\n".join(route_stubs) if route_stubs else "# No endpoints defined"

    return f'''"""
{project_name}/routes.py
API route definitions (generated stubs — implement business logic here)
"""
from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy.orm import Session

from database import get_db
import models

router = APIRouter(prefix="/api/v1")


{stubs_str}
'''


def _render_database(tech: dict) -> str:
    db_url_default = "postgresql://user:password@localhost:5432/dbname"
    queue = tech.get("queue", "")
    redis_block = """
import redis

_redis_client = None

def get_redis():
    global _redis_client
    if _redis_client is None:
        _redis_client = redis.from_url(os.getenv("REDIS_URL", "redis://localhost:6379"))
    return _redis_client
""" if "redis" in queue.lower() else ""

    return f'''"""
{{}}/database.py
SQLAlchemy + optional Redis setup
"""
import os
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, sessionmaker

DATABASE_URL = os.getenv("DATABASE_URL", "{db_url_default}")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
{redis_block}
'''


def _render_requirements(tech: dict) -> str:
    deps = [
        "fastapi==0.111.0",
        "uvicorn[standard]==0.29.0",
        "sqlalchemy==2.0.30",
        "psycopg2-binary==2.9.9",
        "pydantic==2.7.1",
        "python-dotenv==1.0.1",
        "python-multipart==0.0.9",
        "alembic==1.13.1",
    ]
    if "jwt" in str(tech).lower():
        deps += ["python-jose[cryptography]==3.3.0", "passlib[bcrypt]==1.7.4"]
    if "redis" in str(tech).lower():
        deps += ["redis==5.0.4", "celery==5.4.0"]
    if "scikit" in str(tech).lower() or "ml" in str(tech).lower():
        deps += ["scikit-learn==1.5.0", "pandas==2.2.2", "numpy==1.26.4"]
    return "\n".join(deps) + "\n"


def _render_env_example(tech: dict) -> str:
    lines = [
        "# Copy this to .env and fill in real values",
        "",
        "DATABASE_URL=postgresql://user:password@localhost:5432/dbname",
        "SECRET_KEY=your-secret-key-here",
        "CORS_ORIGINS=http://localhost:3000",
        "ANTHROPIC_API_KEY=your-anthropic-key",
    ]
    if "redis" in str(tech).lower():
        lines.append("REDIS_URL=redis://localhost:6379")
    if "oauth" in str(tech).lower() or "google" in str(tech).lower():
        lines += ["GOOGLE_CLIENT_ID=your-google-client-id",
                  "GOOGLE_CLIENT_SECRET=your-google-client-secret"]
    return "\n".join(lines) + "\n"


def _render_docker_compose(project_name: str, tech: dict) -> str:
    redis_service = """
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
""" if "redis" in str(tech).lower() else ""

    redis_depends = "\n      - redis" if "redis" in str(tech).lower() else ""

    return f"""version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db{redis_depends}
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: {project_name}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
{redis_service}
volumes:
  postgres_data:
"""


def _render_readme(
    project_name: str,
    idea: str,
    arch: str,
    services: list,
    endpoints: list,
    tech: dict,
) -> str:
    endpoints_md = "\n".join(f"- `{ep}`" for ep in endpoints)
    services_md  = "\n".join(f"- `{s}`" for s in services)
    tech_md      = "\n".join(f"- **{k.capitalize()}**: {v}" for k, v in tech.items())

    return f"""# {project_name.replace("_", " ").title()} API

> Generated by **AI Co-Founder Team** from idea: *"{idea}"*

## Architecture
{arch}

## Services
{services_md or "- monolith"}

## Tech Stack
{tech_md}

## Endpoints
{endpoints_md}

## Getting Started

```bash
# 1. Clone & enter directory
cd {project_name}

# 2. Create virtual environment
python -m venv .venv && source .venv/bin/activate

# 3. Install dependencies
pip install -r requirements.txt

# 4. Configure environment
cp .env.example .env
# Edit .env with your real values

# 5. Start with Docker Compose (recommended)
docker-compose up --build

# OR start manually
uvicorn main:app --reload
```

API docs available at: http://localhost:8000/docs

## Database Migrations
```bash
alembic init alembic
alembic revision --autogenerate -m "initial"
alembic upgrade head
```

---
*This skeleton was generated automatically. Implement the TODO stubs in `routes.py`.*
"""


# ─────────────────────────────────────────────────────────────────────────────
# String utilities
# ─────────────────────────────────────────────────────────────────────────────

def _to_snake(text: str) -> str:
    """Convert any string to snake_case."""
    text = re.sub(r"[^\w\s]", "", text.lower())
    return re.sub(r"\s+", "_", text.strip())


def _to_pascal(snake: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(word.capitalize() for word in snake.split("_"))


def _path_to_func(method: str, path: str) -> str:
    """Convert HTTP method + path to a Python function name."""
    clean = re.sub(r"[{}]", "", path)
    clean = re.sub(r"[^a-z0-9]+", "_", clean.lower()).strip("_")
    return f"{method}_{clean}"
